server:
  port: 9090

spring:
  application:
    name: shixunapp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shixunapp?allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123456
#  data:
#    redis:
#      host: localhost
#      # password: 123456
#      port: 3306
#      database: 0

# mybatis框架配置信息（对jdbc的封装）
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
